### ISSUE TITLE
[[block]] attributes have been removed from WGSL

### ISSUE THREAD

**Issue by pjmlp** [OmarShehata/webgpu-compute-rasterizer#3]
Quite interesting, thanks for sharing.

Just an heads up, while trying your sample on Chrome 99.0.4763.0, I got the warning message that [[block]] should no longer be applied to structs.

For example,

```
1:3 warning: use of deprecated language feature: [[block]] attributes have been removed from WGSL
[[block]] struct ColorData {
```

**Comment by OmarShehata** [comment]
Thanks @pjmlp ! Yes I had also noticed this just yesterday while wrapping up everything. I couldn't find any more information on this though - should `[[block]]` just be removed? Or does it need to be replaced with something else? Does that lead to any behavior change etc?

I'll need to dig into this a bit more but if anyone knows/has any links that'd be appreciated!

**Comment by pjmlp** [comment]
I just removed `[[block]]` from the shaders and it kept working.

In any case, I was able to dig this out. maybe it helps,

https://github.com/gpuweb/gpuweb/issues/2188

https://github.com/gpuweb/gpuweb/wiki/WGSL-2021-10-19-Minutes#storage-variables-shouldnt-be-required-to-be-structs-2188

**Comment by OmarShehata** [comment]
Thanks!

So it looks like that linked issue is slightly different. That's talking about how instead of doing this:

```wgsl
[[block]] struct ColorData {
  data : array<u32>;
};

[[group(0), binding(1)]] var<storage, read> finalColorBuffer : ColorData;
```

We could replace it directly with:

```wgsl
[[group(0), binding(1)]] var<storage, read> finalColorBuffer : array<u32>;
```

This is the PR where `[[block]]` is deprecated, and links to discussions on it: https://github.com/gpuweb/gpuweb/pull/2104. It looks like it was originally required because the engine needs to know if a struct is used as a type for a binding...but that now it will be inferred automatically. So it should be safe to just remove.

However, I'm going to wait a bit because removing it now breaks the app in Edge Canary, which I'm stuck testing with because Chrome Canary currently doesn't work for me due to this crash: https://bugs.chromium.org/p/chromium/issues/detail?id=1279617

**Comment by OmarShehata** [comment]
Updated to latest WGSL with this commit https://github.com/OmarShehata/webgpu-compute-rasterizer/commit/d23642cc21c491fd0a844afa3167a931e3c9a0d5
